spring.application.name=Portafolio

server.port=8080
#para definir el puerto donde "escuchará" el servidor

logging.pattern.dateformat=hh:mm
#Para definir el formato de despliegue de fecha/hora del log en la consola

spring.main.banner-mode=off
#Para eliminar mensajes invasivos de Spring

spring.thymeleaf.cache=false
#En desarrollo el "cache" del servidor (false), en producción "true"
